spring:
  profiles: local
logging:
  config: classpath:logback-spring.xml
internal:
  elastic:
    host: localhost
    port: 9200
---
spring:
  profiles: localLive
logging:
  config: classpath:logback-spring.xml
internal:
  elastic:
    host: localhost
    port: 9200